services:
  - type: web
    name: shinkeisuijaku-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
    buildFilter:
      paths:
        - requirements.txt
        - app.py
        - templates/**
        - render.yaml 